# CB-Core Database Connection Configuration

iceberg_catalog:
  catalog_name: jdbc_prod
  catalog_impl: org.apache.iceberg.jdbc.JdbcCatalog
  jdbc_uri: jdbc:postgresql://localhost:5432/jdbc_catalog_db
  jdbc_user: jdbc_user
  jdbc_password: jdbc_password
  warehouse_path: /data2/systems/data/jdbc_warehouse
  properties:
    write.metadata.delete-after-commit.enabled: "true"
    write.metadata.previous-versions-max: "5"
    jdbc.schema-version: "V1"

postgresql_operational:
  jdbc_url: jdbc:postgresql://192.168.0.74:5432/boards
  user: spark_user
  password: spark_password
  driver: org.postgresql.Driver
  properties:
    ssl: "false"
    applicationName: "CB-Core"

spark_optimized:
  driver_memory: 4g
  driver_cores: 1
  executor_instances: 2
  executor_cores: 3
  executor_memory: 8g
  executor_memory_overhead: 2g
  
spark_minimal:
  driver_memory: 2g
  driver_cores: 1
  executor_instances: 1
  executor_cores: 2
  executor_memory: 4g
